### ISSUE TITLE
Add to existing dataset 

### ISSUE THREAD

**Issue by kristinecpi** [propublica/django-collaborative#62]
Public Integrity is using JotForm and manually uploading responses each day. Is there a way we can add to our existing dataset without creating a new group?

**Comment by brandonrobertz** [comment]
@kristinecpi How are you currently doing the manual update process? I need to know a little more about what you're doing and what's not working in order to answer, because there's a few ways to update data in Collaborate.

**Comment by jsmithhopkins** [comment]
Hi, @brandonrobertz! I'm working with @kristinecpi on the project. We're using JotForm and had been planning to download the data and upload as a csv to Collaborate. We can't figure out how to do that without creating a new group. The "add data" option within the group appears to just allow metadata additions, and the "new data" option creates a new group.

**Comment by brandonrobertz** [comment]
Right now upload CSV file can only be done once. The system is really optimized for pulling data from a remote spreadsheet and keeping itself up-to-date from there. Might I suggest uploading this CSV to Google Sheets and having Collaborate update from that sheet?

It's not impossible to add CSV file updating, but there are a few technical limitations that would make this not-so-straightforward.

**Comment by jsmithhopkins** [comment]
Ah, shoot -- we were hoping to avoid Google Sheets because of privacy concerns. The data we're uploading are survey responses with personal information. (We do have G Suite, which I hear is better on privacy, so I'm asking our tech expert to determine whether that's safe.)

It would be great, though, to know what the CSV file updating protocol is in case we can do that instead.

Thank you!

**Comment by brandonrobertz** [comment]
@jsmithhopkins The Google Sheet/CSV URL updating works like this:

Initial import:

1) In the main "import" wizard, you put in a link to your sheet/CSV (and optionally Google credentials, so only Collaborate has access).
2) We do an initial import on the following screen.

Subsequent updates:

3) If you have the background updater running, it will check the sheet/URL and import any new records found. If you don't have the background updater running, this will happen when you click "re-import" and do that process.

The problem with updating local CSV files is you need to go through the main wizard to get a file uploader, but that wizard currently only supports creating new datasets or updating from remote ones.

So a long term solution here would be to modify the re-import screen to allow for adding an updated CSV file.

In the meantime, and this is a total hack, the quickest way for you to get this local file update working would be to serve the CSV locally/privately (e.g., https//localhost:8000/my_data.csv) and point Collaborate at that file via CSV URL. I don't know what your deployment looks like, though, so this might not be an option.

**Comment by jsmithhopkins** [comment]
Thank you, @brandonrobertz, I'll pass your instructions on to our IT director and cross my fingers! Really appreciate it.

**Comment by jsmithhopkins** [comment]
We're still working through this, but one thing we tried was the idea of hosting the csv on our cloud server -- making the link public for the short amount of time Collaborate needs to refresh the data, but otherwise keeping it private. I would need to upload a new version of the csv to the server on a regular basis as new survey responses come in, which is OK, and the csv link remains the same throughout. However, when I tested this with Collaborate, it went through the refresh-data process but did not actually pull the additional data in. It didn't throw an error message. It just had me click through the "here are your columns" step, and at the end, nothing had changed.

All ears if you have thoughts about what might be the hitch. Thanks!

**Comment by brandonrobertz** [comment]
@jsmithhopkins To clarify: when you looked at your admin list view after importing, you couldn't find any additional rows?

**Comment by jsmithhopkins** [comment]
That's correct. Since then, a colleague gave it a try and it worked -- but it took several hours for the additional rows to show up. Same thing happened to me earlier today when I tested it myself. I'm in the midst of another test; the additional rows haven't appeared yet, but it's only been an hour or two. It shouldn't take that long, I'm guessing?

**Comment by brandonrobertz** [comment]
Are you using large datasets by any chance? There's a limitation to the in-request import, to prevent server timeouts and crashes. The background updater has to be used to datasets that take more than a couple seconds to load, which would explain your update delay.

**Comment by jsmithhopkins** [comment]
For these tests, we're using small datasets -- less than 25 rows (but there _are_ lots of columns, roughly 80).

For future reference: If I ask Collaborate to refresh from an 80-column dataset with, say, 20 new rows of information and 200 rows it already has, any idea how long that might take? I would have to keep the dataset set to public during that period, so I'm wondering if we're talking about a few minutes or really several hours. 

Thanks!

**Comment by jsmithhopkins** [comment]
I just did another test (same number of columns, 17 rows, 4 of them new), and Collaborate showed the new rows in about a minute this time. I'm perplexed! I mean, it's great, I just don't know why it took so much longer before or if we'll have delay issues normally. The faster, the better, so we can keep the data source as locked down as possible.

**Comment by brandonrobertz** [comment]
If you're using datasets with less than a few thousand records, it should update in the re-import request. Do you have access to the logs? Collaborate outputs information upon re-import if there are any errors.

The random delays is weird, though. If you're not using the background updater and there's no errors in the import logs, I wonder if it's some kind of caching issue?

**Comment by brandonrobertz** [comment]
I think, for this use case, allowing adding an updated file on the re-import screen is the solution. Let me look through the code and see how much work this might be.

**Comment by jsmithhopkins** [comment]
The "log entries" section? I can see that, and there are no references to errors there. (Happy to look elsewhere if that's not the right spot.)

Thank you so much for offering to look through the code to determine if that addition would be relatively simple! I'd be really grateful to be able to make Collaborate work for the project we've got. I can't think of a workable Plan B.

**Comment by brandonrobertz** [comment]
> The "log entries" section? I can see that, and there are no references to errors there. (Happy to look elsewhere if that's not the right spot.)

By log entries, I mean in your server logs running the Collaborate web app (nginx, gunicorn, apache, etc, depending on your deployment).

**Comment by jsmithhopkins** [comment]
Ah, I don't have access to those, but I'll pass that on to the folks who do. Thank you!

**Comment by brandonrobertz** [comment]
Okay, I went through the code and it turned out that getting CSV file updating was pretty easy. I added it to the master branch (https://github.com/propublica/django-collaborative/commit/542f6925e855f6183266764b412d3af328dcc291
) and tested it on some files I have here.

Some important considerations:
- Your CSV file must always have a consistent set of headers
- You cannot remove rows from this CSV file. The row is the primary key and changing this will cause major problems.

When you go to the re-import screen, you'll see an uploader with some text. That's where you upload your updated CSVs.

Let me know how this works!

**Comment by jsmithhopkins** [comment]
That's so great, thank you! Our data folks were in the midst of reinstalling Collaborate to see if perhaps something about the way we were running it was causing hiccups, so I can't test it just yet. But I'll let you know as soon as I can. Starting from scratch, should I choose the "file upload (CSV)" option, and then when I select the "re-import" button, I'll get this new option you mention?

**Comment by brandonrobertz** [comment]
Yes choose file upload (CSV) again. You'll now have an option to add an updated file on the re-import screen.

**Comment by jsmithhopkins** [comment]
Fingers crossed -- I think it's working! Uploaded a file minus three of the current rows, then reimported with all the rows. Collaborate brought it in just fine. Thank you so very much for adding this option! It's incredibly helpful.

**Comment by brandonrobertz** [comment]
Awesome! I'm gonna close this issue, then.

**Comment by jsmithhopkins** [comment]
Oh dang. @brandonrobertz, I didn't think to check that the tagging, etc., remained in place after reimports, and I just noticed that the "status" and "assigned to" information migrates. 

This morning, after importing the dataset with one additional response compared with yesterday, the status/assignment info associated with the first item suddenly appeared on the second item. I fixed that, thinking I'd just made a mistake. But this afternoon, when I reimported with several more new responses, the information had migrated several items down. I don't suppose that's an easy fix?

In every other way I can see, the reimporting works perfectly.

**Comment by brandonrobertz** [comment]
You're adding new records to the bottom of the CSV, yes?

**Comment by jsmithhopkins** [comment]
Ah, that was the problem! Sorry, I didn't realize the order of the rows was important as long as all the original rows remained in place. My data downloads from the survey platform with the newest records on top, so I just tried again the other way. Worked exactly as it should. Thank you!

**Comment by brandonrobertz** [comment]
The row number is the primary key of (how we look up and name) records, so you need to make sure the row number/record relationship always stays the same. Glad everything's working!

**Comment by jsmithhopkins** [comment]
Thanks, makes sense!
