### ISSUE TITLE
Responses not populating in Collaborate via Google Sheet import

### ISSUE THREAD

**Issue by maya-miller-engagement** [propublica/django-collaborative#66]
Hey Brandon! Having another small bug in the project "longtermcare ctp". A handful of fields are not populating in Collaborate, including the following:
- "Please explain how you know this."
- "Please provide us with as much detail as you're comfortable with about the person and the circumstances around their death."

And a handful of others. Here's the Google Sheet that is feeding the form, which you're shared on: [redacted!]

Let me know if you want to chat through this on the phone -- I'm around if need be! Thanks,

Maya

**Comment by brandonrobertz** [comment]
I found the problem and am testing a fix. I think I'll have it ready to go tomorrow afternoon.

**Comment by brandonrobertz** [comment]
I pushed a fix for this issue.

For future reference to other developers:

The problem was the way CSVKit's CSVSQL command was being called. By default, CSVSQL provides the `--doublequote` and `--skipinitialspace` settings via a utility function in `__init__.py`. This wasn't being called because it fails to load when being called from inside a Django request. I copied the calls to the CSVSQL argument utility function from their init into the one we use for calling CSVSQL. Now escaping of special characters should work as expected, using CSVSQL defaults (and will future proof collaborate if CSVSQL changes their defaults).

This is released as [v1.1.1](https://github.com/propublica/django-collaborative/releases/tag/v1.1.1)
